spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telehackdb
    username: telehack
    password: telehack
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

server:
  forward-headers-strategy: framework